name: Build an app

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - shell: bash
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET}}
        run: |
          echo "API_KEY=$API_KEY" >> secrets.properties
          echo "API_SECRET=$API_SECRET" >> secrets.properties
      
      - name: Build project
        run: ./gradlew assemble
      - name: Upload debug version
        uses: actions/upload-artifact@v2
        with: 
          name: debug
          path: app/build/outputs/apk/debug/*
